# Generated by Django 2.2 on 2020-04-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading_title', models.CharField(max_length=50)),
                ('blog_heading_message', models.CharField(max_length=150)),
            ],
        ),
    ]
