# Generated by Django 2.2 on 2020-04-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_header_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header_blog',
            options={'verbose_name': 'Header Blog', 'verbose_name_plural': 'Heades Blog'},
        ),
    ]
