# Generated by Django 2.2 on 2020-04-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200408_0025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header_Blog',
            new_name='HeaderBlog',
        ),
        migrations.AlterModelOptions(
            name='headerblog',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Headers'},
        ),
        migrations.AlterModelTable(
            name='headerblog',
            table='HeaderBlog',
        ),
    ]
