# Generated by Django 2.2 on 2020-05-01 21:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_heading_title', models.CharField(max_length=50)),
                ('events_heading_message', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'db_table': 'HeaderEvents',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='event-slug', max_length=255, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='events/default.jpg', upload_to='events')),
                ('short_content', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=6)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('speakers', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
    ]
