# Generated by Django 2.2 on 2020-04-29 10:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_heading_title', models.CharField(max_length=50)),
                ('notice_heading_message', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'HeaderNotice',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='notice-slug', max_length=255, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=200)),
                ('notice_date', models.DateField()),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('informations', models.ManyToManyField(to='notice.Information')),
            ],
        ),
    ]
