# Generated by Django 2.2 on 2020-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
