# Generated by Django 2.2 on 2020-05-03 17:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0002_auto_20200503_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.RemoveField(
            model_name='baner',
            name='content',
        ),
        migrations.RemoveField(
            model_name='baner',
            name='title',
        ),
    ]
