# Generated by Django 2.2 on 2020-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0004_auto_20200503_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
