# Generated by Django 2.2 on 2020-05-03 20:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0005_auto_20200503_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('image', models.ImageField(default='home/success-story.jpg', upload_to='home')),
                ('video', models.CharField(max_length=200)),
            ],
        ),
    ]
