# Generated by Django 2.2 on 2020-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0006_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
