# Generated by Django 2.2 on 2020-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0007_auto_20200503_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='themify_icons',
            field=models.CharField(default='ti-face-smile', max_length=15),
        ),
    ]
