# Generated by Django 2.2 on 2020-04-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headernotice',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Headers'},
        ),
    ]
