# Generated by Django 2.2 on 2020-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funfacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading_title', models.CharField(max_length=50)),
                ('about_heading_message', models.CharField(max_length=150)),
                ('image', models.ImageField(default='about/default.jpg', upload_to='about')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('stories_title', models.CharField(max_length=50)),
                ('stories_content', models.TextField()),
                ('story_backgroung', models.ImageField(default='about/default.jpg', upload_to='about')),
                ('video', models.CharField(max_length=50)),
                ('title_people', models.CharField(max_length=50)),
                ('funfacts', models.ManyToManyField(to='about.Funfacts')),
                ('peoples', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
    ]
