# Generated by Django 2.2 on 2020-04-29 22:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stories_content',
            field=tinymce.models.HTMLField(verbose_name='Stories Content'),
        ),
    ]
