# Generated by Django 2.2 on 2020-04-28 21:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_heading_title', models.CharField(max_length=50)),
                ('research_heading_message', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'db_table': 'HeaderResearch',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('image', models.ImageField(default='research/default.png', upload_to='research')),
            ],
        ),
    ]
