# Generated by Django 2.2 on 2020-04-29 22:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
