# Generated by Django 2.2 on 2020-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='story_backgroung',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
    ]
