# Generated by Django 2.2 on 2020-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200406_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=50),
        ),
    ]
