# Generated by Django 2.2 on 2020-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200406_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='users'),
        ),
    ]
