# Generated by Django 2.2 on 2020-04-23 16:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200410_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=tinymce.models.HTMLField(verbose_name='Biography'),
        ),
    ]
