# Generated by Django 2.2 on 2020-04-23 21:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200423_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
