# Generated by Django 2.2 on 2020-04-16 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20200410_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Apply',
                'verbose_name_plural': 'Apply',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='HeaderCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_heading_title', models.CharField(max_length=50)),
                ('courses_heading_message', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'db_table': 'HeaderCourses',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_content', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='courses/')),
                ('course_date', models.DateField()),
                ('duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('about_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('fees_and_funding', models.TextField()),
                ('apply', models.ManyToManyField(to='courses.Apply')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Category')),
                ('requirements', models.ManyToManyField(to='courses.Requirements')),
                ('teacher', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
    ]
