# Generated by Django 2.2 on 2020-04-29 22:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesandfunding',
            name='fees_and_funding',
            field=tinymce.models.HTMLField(verbose_name='Fees And Funding'),
        ),
    ]
