# Generated by Django 2.2 on 2020-04-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200416_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAndFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_and_funding', models.TextField()),
            ],
            options={
                'verbose_name': 'Fees And Funding',
                'verbose_name_plural': 'Fees And Funding',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees_and_funding',
        ),
        migrations.AddField(
            model_name='course',
            name='fees_and_funding',
            field=models.ManyToManyField(to='courses.FeesAndFunding'),
        ),
    ]
