# Generated by Django 2.2 on 2020-04-27 12:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200427_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
