# Generated by Django 2.2 on 2020-05-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200429_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
