# Generated by Django 2.2 on 2020-04-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200416_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_content',
            field=models.CharField(max_length=200),
        ),
    ]
