# Generated by Django 2.2 on 2020-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200416_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(),
        ),
    ]
