# Generated by Django 2.2 on 2020-04-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200416_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_date',
            field=models.DateTimeField(),
        ),
    ]
