# Generated by Django 2.2 on 2020-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200511_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=130),
        ),
    ]
