# Generated by Django 2.2 on 2020-05-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecenter', '0003_auto_20200503_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='baner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecenter.Baner'),
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecenter.Slider'),
        ),
    ]
